CREATE EXTERNAL TABLE cloudtrail_log (

     `Records` array<
        struct<
            `additionalEventData`:struct<
                `AuthenticationMethod`:string,
                `CipherSuite`:string,
                `LakeFormationTrustedCallerInvocation`:string,
                `SignatureVersion`:string,
                `insufficientLakeFormationPermissions`:array<
                    string>,
                `lakeFormationPrincipal`:string,
                `x-amz-id-2`:string>,
            `apiVersion`:string,
            `awsRegion`:string,
            `errorCode`:string,
            `errorMessage`:string,
            `eventID`:string,
            `eventName`:string,
            `eventSource`:string,
            `eventTime`:string,
            `eventType`:string,
            `eventVersion`:string,
            `readOnly`:boolean,
            `recipientAccountId`:string,
            `requestID`:string,
            `requestParameters`:struct<
                `AssociateIamInstanceProfileRequest`:struct<
                    `IamInstanceProfile`:struct<
                        `Arn`:string,
                        `Name`:string>,
                    `InstanceId`:string>,
                `CreateBucketConfiguration`:struct<
                    `LocationConstraint`:string,
                    `xmlns`:string>,
                `DescribeCapacityReservationsRequest`:struct<
                    `Filter`:struct<
                        `Name`:string,
                        `Value`:struct<
                            `content`:string,
                            `tag`:bigint>,
                        `tag`:bigint>,
                    `MaxResults`:bigint>,
                `DescribeCoipPoolsRequest`:struct<
                    `MaxResults`:bigint>,
                `DescribeEgressOnlyInternetGatewaysRequest`:struct<
                    `MaxResults`:bigint>,
                `DescribeHostsRequest`:struct<
                    `Filter`:struct<
                        `Name`:string,
                        `Value`:array<
                            struct<
                                `content`:string,
                                `tag`:bigint>>,
                        `tag`:bigint>,
                    `MaxResults`:bigint>,
                `DescribeIamInstanceProfileAssociationsRequest`:struct<
                    `Filter`:struct<
                        `Name`:string,
                        `Value`:struct<
                            `content`:string,
                            `tag`:bigint>,
                        `tag`:bigint>>,
                `DescribeInstanceCreditSpecificationsRequest`:struct<
                    `InstanceId`:struct<
                        `content`:string,
                        `tag`:bigint>>,
                `DescribeInstanceTypesRequest`:struct<
                    `MaxResults`:bigint,
                    `NextToken`:string>,
                `DescribeLaunchTemplatesRequest`:struct<
                    `MaxResults`:bigint>,
                `DescribeManagedPrefixListsRequest`:struct<
                    `MaxResults`:bigint>,
                `DescribeNatGatewaysRequest`:struct<
                    `Filter`:array<
                        struct<
                            `Name`:string,
                            `Value`:string,
                            `tag`:bigint>>,
                    `MaxResults`:bigint>,
                `DescribeStaleSecurityGroupsRequest`:struct<
                    `MaxResults`:bigint,
                    `VpcId`:string>,
                `DescribeVolumesModificationsRequest`:struct<
                    `MaxResults`:bigint>,
                `DescribeVpcEndpointServiceConfigurationsRequest`:struct<
                    `MaxResults`:bigint>,
                `DescribeVpcEndpointsRequest`:struct<
                    `Filter`:struct<
                        `Name`:string,
                        `Value`:struct<
                            `content`:string,
                            `tag`:bigint>,
                        `tag`:bigint>,
                    `MaxResults`:bigint>,
                `Filters`:array<
                    struct<
                        `Name`:string,
                        `Values`:array<
                            string>>>,
                `GetDefaultCreditSpecificationRequest`:struct<
                    `InstanceFamily`:string>,
                `GetEbsEncryptionByDefaultRequest`:string,
                `GroupName`:string,
                `Host`:string,
                `PublicAccessBlockConfiguration`:struct<
                    `BlockPublicAcls`:boolean,
                    `BlockPublicPolicy`:boolean,
                    `IgnorePublicAcls`:boolean,
                    `RestrictPublicBuckets`:boolean,
                    `xmlns`:string>,
                `X-Amz-Algorithm`:string,
                `X-Amz-Date`:string,
                `X-Amz-Expires`:string,
                `X-Amz-SignedHeaders`:string,
                `accountAttributeNameSet`:struct<
                    `items`:array<
                        struct<
                            `attributeName`:string>>>,
                `acl`:string,
                `allocatedStorage`:bigint,
                `allowMajorVersionUpgrade`:boolean,
                `applications`:array<
                    struct<
                        `args`:array<
                            string>,
                        `name`:string>>,
                `applyImmediately`:boolean,
                `attribute`:string,
                `auditContext`:struct<
                    `additionalAuditContext`:string>,
                `autoMinorVersionUpgrade`:boolean,
                `availabilityZone`:string,
                `backupRetentionPeriod`:bigint,
                `blockDeviceMapping`:struct<
                    `items`:array<
                        struct<
                            `deviceName`:string,
                            `ebs`:struct<
                                `deleteOnTermination`:boolean,
                                `volumeSize`:bigint,
                                `volumeType`:string>>>>,
                `bootstrapActions`:array<
                    string>,
                `bucket`:string,
                `bucketName`:string,
                `capabilities`:array<
                    string>,
                `capacityReservationSpecification`:struct<
                    `capacityReservationPreference`:string>,
                `catalogId`:string,
                `changeSetName`:string,
                `cidrBlock`:string,
                `cidrIp`:string,
                `clientRequestToken`:string,
                `clientToken`:string,
                `clusterId`:string,
                `configurations`:array<
                    struct<
                        `classification`:string,
                        `configurations`:array<
                            string>,
                        `properties`:struct<
                            `hive.metastore.client.factory.class`:string>>>,
                `copyTagsToSnapshot`:boolean,
                `creditSpecification`:struct<
                    `cpuCredits`:string>,
                `dBInstanceClass`:string,
                `dBInstanceIdentifier`:string,
                `dBParameterGroupName`:string,
                `dBSubnetGroupDescription`:string,
                `dBSubnetGroupName`:string,
                `databaseInput`:struct<
                    `locationUri`:string,
                    `name`:string>,
                `databaseName`:string,
                `defaultOnly`:boolean,
                `deleteAutomatedBackups`:boolean,
                `deletionProtection`:boolean,
                `description`:string,
                `destinationCidrBlock`:string,
                `dhcpOptionsSet`:struct<
                    `items`:array<
                        struct<
                            `dhcpOptionsId`:string>>>,
                `disableApiTermination`:boolean,
                `disableRollback`:boolean,
                `documentName`:string,
                `documentVersion`:string,
                `duration`:bigint,
                `durationSeconds`:bigint,
                `ebsOptimized`:boolean,
                `ebsRootVolumeSize`:bigint,
                `enableCloudwatchLogsExports`:array<
                    string>,
                `enableDnsHostnames`:struct<
                    `value`:boolean>,
                `enableDnsSupport`:struct<
                    `value`:boolean>,
                `enablePerformanceInsights`:boolean,
                `encryption`:string,
                `endTime`:bigint,
                `engine`:string,
                `engineName`:string,
                `engineVersion`:string,
                `expression`:string,
                `filterSet`:struct<
                    `items`:array<
                        struct<
                            `name`:string,
                            `valueSet`:struct<
                                `items`:array<
                                    struct<
                                        `value`:string>>>>>>,
                `filters`:array<
                    struct<
                        `key`:string,
                        `name`:string,
                        `values`:array<
                            string>>>,
                `force`:boolean,
                `fromPort`:bigint,
                `gatewayId`:string,
                `groupDescription`:string,
                `groupId`:string,
                `groupName`:string,
                `groupSet`:struct<
                    `items`:array<
                        struct<
                            `groupId`:string,
                            `groupName`:string>>>,
                `hibernationOptions`:struct<
                    `configured`:boolean>,
                `iamInstanceProfile`:struct<
                    `name`:string>,
                `imagesSet`:struct<
                    `items`:array<
                        struct<
                            `imageId`:string>>>,
                `includeAll`:boolean,
                `includeAllInstances`:boolean,
                `includePublic`:boolean,
                `includeShadowTrails`:boolean,
                `includeShared`:boolean,
                `instanceGroupTypes`:array<
                    string>,
                `instanceId`:string,
                `instanceInitiatedShutdownBehavior`:string,
                `instanceTenancy`:string,
                `instanceType`:string,
                `instances`:struct<
                    `additionalMasterSecurityGroups`:array<
                        string>,
                    `additionalSlaveSecurityGroups`:array<
                        string>,
                    `ec2KeyName`:string,
                    `ec2SubnetId`:string,
                    `ec2SubnetIds`:array<
                        string>,
                    `emrManagedMasterSecurityGroup`:string,
                    `emrManagedSlaveSecurityGroup`:string,
                    `hadoopVersion`:string,
                    `instanceFleets`:array<
                        string>,
                    `instanceGroups`:array<
                        struct<
                            `configurations`:array<
                                string>,
                            `ebsConfiguration`:struct<
                                `ebsBlockDeviceConfigs`:array<
                                    struct<
                                        `volumeSpecification`:struct<
                                            `sizeInGB`:bigint,
                                            `volumeType`:string>,
                                        `volumesPerInstance`:bigint>>>,
                            `instanceCount`:bigint,
                            `instanceRole`:string,
                            `instanceType`:string,
                            `market`:string,
                            `name`:string>>,
                    `keepJobFlowAliveWhenNoSteps`:boolean,
                    `terminationProtected`:boolean>,
                `instancesSet`:struct<
                    `item`:array<
                        struct<
                            `instanceId`:string>>,
                    `items`:array<
                        struct<
                            `imageId`:string,
                            `instanceId`:string,
                            `keyName`:string,
                            `maxCount`:bigint,
                            `minCount`:bigint>>>,
                `internetGatewayId`:string,
                `ipPermissions`:struct<
                    `items`:array<
                        struct<
                            `fromPort`:bigint,
                            `groups`:struct<
                                `items`:array<
                                    struct<
                                        `groupId`:string>>>,
                            `ipProtocol`:string,
                            `ipRanges`:struct<
                                `items`:array<
                                    struct<
                                        `cidrIp`:string,
                                        `description`:string>>>,
                            `toPort`:bigint>>>,
                `ipProtocol`:string,
                `ipv6AddressCount`:bigint,
                `jobFlowIds`:array<
                    string>,
                `jobFlowRole`:string,
                `key`:string,
                `keyName`:string,
                `keySet`:struct<
                    `items`:array<
                        struct<
                            `keyName`:string>>>,
                `licenseModel`:string,
                `lifecycle`:string,
                `limit`:bigint,
                `listSupportedCharacterSets`:boolean,
                `listSupportedTimezones`:boolean,
                `location`:string,
                `logGroupName`:string,
                `logStreamName`:string,
                `logUri`:string,
                `logging`:string,
                `majorEngineVersion`:string,
                `mapPublicIpOnLaunch`:struct<
                    `value`:boolean>,
                `marker`:string,
                `masterUserPassword`:string,
                `masterUsername`:string,
                `maxAllocatedStorage`:bigint,
                `maxRecords`:bigint,
                `maxResults`:string,
                `metadataOptions`:struct<
                    `httpEndpoint`:string,
                    `httpPutResponseHopLimit`:bigint,
                    `httpTokens`:string>,
                `mode`:string,
                `monitoring`:struct<
                    `enabled`:boolean>,
                `name`:string,
                `networkInterfaceId`:string,
                `networkInterfaceSet`:struct<
                    `items`:array<
                        struct<
                            `associatePublicIpAddress`:boolean,
                            `deleteOnTermination`:boolean,
                            `description`:string,
                            `deviceIndex`:bigint,
                            `groupSet`:struct<
                                `items`:array<
                                    struct<
                                        `groupId`:string>>>,
                            `ipv6AddressCount`:bigint,
                            `subnetId`:string>>>,
                `nextToken`:string,
                `notification`:string,
                `notificationARNs`:array<
                    string>,
                `object-lock`:string,
                `optionGroupDescription`:string,
                `optionGroupName`:string,
                `optionsToInclude`:array<
                    struct<
                        `optionName`:string,
                        `optionSettings`:array<
                            struct<
                                `isCollection`:boolean,
                                `isModifiable`:boolean,
                                `name`:string,
                                `value`:string>>>>,
                `orderByAscend`:boolean,
                `ownersSet`:struct<
                    `items`:array<
                        struct<
                            `owner`:string>>>,
                `pageSize`:bigint,
                `paginationToken`:string,
                `parameters`:string,
                `partNumber`:string,
                `pattern`:string,
                `policy`:string,
                `policyStatus`:string,
                `port`:bigint,
                `productDescriptionSet`:struct<
                    `items`:array<
                        struct<
                            `productDescription`:string>>>,
                `publicAccessBlock`:string,
                `publiclyAccessible`:boolean,
                `queryExecutionContext`:struct<
                    `catalog`:string,
                    `database`:string>,
                `queryExecutionId`:string,
                `queryExecutionIds`:array<
                    string>,
                `queryString`:string,
                `releaseLabel`:string,
                `replication`:string,
                `resourceARNList`:array<
                    string>,
                `resourceName`:string,
                `resourceTypeFilters`:array<
                    string>,
                `resourcesPerPage`:bigint,
                `resourcesSet`:struct<
                    `items`:array<
                        struct<
                            `resourceId`:string>>>,
                `resultConfiguration`:struct<
                    `outputLocation`:string>,
                `roleArn`:string,
                `roleSessionName`:string,
                `routeTableId`:string,
                `securityGroupIdSet`:struct<
                    `items`:array<
                        struct<
                            `groupId`:string>>>,
                `segment`:struct<
                    `segmentNumber`:bigint,
                    `totalSegments`:bigint>,
                `serviceRole`:string,
                `sharedUsersSet`:struct<
                    `items`:array<
                        struct<
                            `user`:string>>>,
                `skipFinalSnapshot`:boolean,
                `snapshotSet`:struct<
                    `items`:array<
                        struct<
                            `snapshotId`:string>>>,
                `sourceId`:string,
                `stackName`:string,
                `stackStatusFilter`:array<
                    string>,
                `startTime`:bigint,
                `stepConcurrencyLevel`:bigint,
                `steps`:array<
                    struct<
                        `actionOnFailure`:string,
                        `hadoopJarStep`:struct<
                            `args`:array<
                                string>,
                            `jar`:string,
                            `properties`:array<
                                string>>,
                        `name`:string>>,
                `storageEncrypted`:boolean,
                `storageType`:string,
                `subnetId`:string,
                `subnetIds`:array<
                    string>,
                `subnetSet`:struct<
                    `items`:array<
                        struct<
                            `subnetId`:string>>>,
                `tableInput`:struct<
                    `lastAccessTime`:string,
                    `name`:string,
                    `owner`:string,
                    `parameters`:struct<
                        `numFiles`:string,
                        `spark.sql.create.version`:string,
                        `spark.sql.sources.provider`:string,
                        `spark.sql.sources.schema.numParts`:string,
                        `spark.sql.sources.schema.part.0`:string,
                        `totalSize`:string,
                        `transient_lastDdlTime`:string,
                        `view.catalogAndNamespace.numParts`:string,
                        `view.catalogAndNamespace.part.0`:string,
                        `view.catalogAndNamespace.part.1`:string,
                        `view.query.out.col.0`:string,
                        `view.query.out.numCols`:string>,
                    `partitionKeys`:array<
                        string>,
                    `retention`:bigint,
                    `storageDescriptor`:struct<
                        `bucketColumns`:array<
                            string>,
                        `columns`:array<
                            struct<
                                `name`:string,
                                `type`:string>>,
                        `compressed`:boolean,
                        `inputFormat`:string,
                        `location`:string,
                        `numberOfBuckets`:bigint,
                        `outputFormat`:string,
                        `serdeInfo`:struct<
                            `parameters`:struct<
                                `path`:string,
                                `serialization.format`:string>,
                            `serializationLibrary`:string>,
                        `skewedInfo`:struct<
                            `skewedColumnNames`:array<
                                string>,
                            `skewedColumnValues`:array<
                                string>>,
                        `sortColumns`:array<
                            string>,
                        `storedAsSubDirectories`:boolean>,
                    `tableType`:string,
                    `viewExpandedText`:string,
                    `viewOriginalText`:string>,
                `tableName`:string,
                `tagFilters`:array<
                    struct<
                        `key`:string,
                        `values`:array<
                            string>>>,
                `tagSet`:struct<
                    `items`:array<
                        struct<
                            `key`:string,
                            `value`:string>>>,
                `tagSpecificationSet`:struct<
                    `items`:array<
                        struct<
                            `resourceType`:string,
                            `tags`:array<
                                struct<
                                    `key`:string,
                                    `value`:string>>>>>,
                `tagging`:string,
                `tags`:string,
                `tagsPerPage`:bigint,
                `targetParameterName`:string,
                `targets`:array<
                    struct<
                        `key`:string,
                        `values`:array<
                            string>>>,
                `templateURL`:string,
                `tenancy`:string,
                `toPort`:bigint,
                `trailNameList`:array<
                    string>,
                `uploadId`:string,
                `userData`:string,
                `versioning`:string,
                `visibleToAllUsers`:boolean,
                `volumeSet`:struct<
                    `items`:array<
                        struct<
                            `volumeId`:string>>>,
                `vpc`:boolean,
                `vpcId`:string,
                `vpcSecurityGroupIds`:array<
                    string>,
                `vpcSet`:struct<
                    `items`:array<
                        struct<
                            `vpcId`:string>>>,
                `website`:string,
                `workGroup`:string>,
            `resources`:array<
                struct<
                    `ARN`:string,
                    `accountId`:string,
                    `type`:string>>,
            `responseElements`:struct<
                `_return`:boolean,
                `allocatedStorage`:bigint,
                `allowsVpcAndNonVpcInstanceMemberships`:boolean,
                `associatedRoles`:array<
                    string>,
                `assumedRoleUser`:struct<
                    `arn`:string,
                    `assumedRoleId`:string>,
                `autoMinorVersionUpgrade`:boolean,
                `automationExecutionId`:string,
                `availabilityZone`:string,
                `backupRetentionPeriod`:bigint,
                `cACertificateIdentifier`:string,
                `characterSetName`:string,
                `clusterArn`:string,
                `copyTagsToSnapshot`:boolean,
                `credentials`:struct<
                    `accessKeyId`:string,
                    `expiration`:string,
                    `sessionToken`:string>,
                `dBInstanceArn`:string,
                `dBInstanceClass`:string,
                `dBInstanceIdentifier`:string,
                `dBInstanceStatus`:string,
                `dBParameterGroups`:array<
                    struct<
                        `dBParameterGroupName`:string,
                        `parameterApplyStatus`:string>>,
                `dBSecurityGroups`:array<
                    string>,
                `dBSubnetGroup`:struct<
                    `dBSubnetGroupDescription`:string,
                    `dBSubnetGroupName`:string,
                    `subnetGroupStatus`:string,
                    `subnets`:array<
                        struct<
                            `subnetAvailabilityZone`:struct<
                                `name`:string>,
                            `subnetIdentifier`:string,
                            `subnetStatus`:string>>,
                    `vpcId`:string>,
                `dBSubnetGroupArn`:string,
                `dBSubnetGroupDescription`:string,
                `dBSubnetGroupName`:string,
                `dataCatalogsSummary`:array<
                    struct<
                        `catalogName`:string,
                        `type`:string>>,
                `dbInstancePort`:bigint,
                `dbiResourceId`:string,
                `deletionProtection`:boolean,
                `description`:string,
                `domainMemberships`:array<
                    string>,
                `endpoint`:struct<
                    `address`:string,
                    `hostedZoneId`:string,
                    `port`:bigint>,
                `engine`:string,
                `engineName`:string,
                `engineVersion`:string,
                `events`:array<
                    struct<
                        `clusterId`:string,
                        `description`:string,
                        `eventType`:string,
                        `resourceId`:string,
                        `resourceType`:string,
                        `severity`:string,
                        `sourceTimeStamp`:string>>,
                `globalClusters`:array<
                    string>,
                `groupId`:string,
                `httpEndpointEnabled`:boolean,
                `iAMDatabaseAuthenticationEnabled`:boolean,
                `id`:string,
                `instanceCreateTime`:string,
                `instancesSet`:struct<
                    `items`:array<
                        struct<
                            `amiLaunchIndex`:bigint,
                            `architecture`:string,
                            `capacityReservationSpecification`:struct<
                                `capacityReservationPreference`:string>,
                            `clientToken`:string,
                            `cpuOptions`:struct<
                                `coreCount`:bigint,
                                `threadsPerCore`:bigint>,
                            `currentState`:struct<
                                `code`:bigint,
                                `name`:string>,
                            `ebsOptimized`:boolean,
                            `enclaveOptions`:struct<
                                `enabled`:boolean>,
                            `groupSet`:struct<
                                `items`:array<
                                    struct<
                                        `groupId`:string,
                                        `groupName`:string>>>,
                            `hibernationOptions`:struct<
                                `configured`:boolean>,
                            `hypervisor`:string,
                            `iamInstanceProfile`:struct<
                                `arn`:string,
                                `id`:string>,
                            `imageId`:string,
                            `instanceId`:string,
                            `instanceState`:struct<
                                `code`:bigint,
                                `name`:string>,
                            `instanceType`:string,
                            `keyName`:string,
                            `launchTime`:bigint,
                            `metadataOptions`:struct<
                                `httpEndpoint`:string,
                                `httpPutResponseHopLimit`:bigint,
                                `httpTokens`:string,
                                `state`:string>,
                            `monitoring`:struct<
                                `state`:string>,
                            `networkInterfaceSet`:struct<
                                `items`:array<
                                    struct<
                                        `attachment`:struct<
                                            `attachTime`:bigint,
                                            `attachmentId`:string,
                                            `deleteOnTermination`:boolean,
                                            `deviceIndex`:bigint,
                                            `status`:string>,
                                        `description`:string,
                                        `groupSet`:struct<
                                            `items`:array<
                                                struct<
                                                    `groupId`:string,
                                                    `groupName`:string>>>,
                                        `interfaceType`:string,
                                        `macAddress`:string,
                                        `networkInterfaceId`:string,
                                        `ownerId`:string,
                                        `privateDnsName`:string,
                                        `privateIpAddress`:string,
                                        `privateIpAddressesSet`:struct<
                                            `item`:array<
                                                struct<
                                                    `primary`:boolean,
                                                    `privateDnsName`:string,
                                                    `privateIpAddress`:string>>>,
                                        `sourceDestCheck`:boolean,
                                        `status`:string,
                                        `subnetId`:string,
                                        `vpcId`:string>>>,
                            `placement`:struct<
                                `availabilityZone`:string,
                                `tenancy`:string>,
                            `platform`:string,
                            `previousState`:struct<
                                `code`:bigint,
                                `name`:string>,
                            `privateDnsName`:string,
                            `privateIpAddress`:string,
                            `rootDeviceName`:string,
                            `rootDeviceType`:string,
                            `sourceDestCheck`:boolean,
                            `stateReason`:struct<
                                `code`:string,
                                `message`:string>,
                            `subnetId`:string,
                            `tagSet`:struct<
                                `items`:array<
                                    struct<
                                        `key`:string,
                                        `value`:string>>>,
                            `virtualizationType`:string,
                            `vpcId`:string>>>,
                `internetGateway`:struct<
                    `internetGatewayId`:string>,
                `jobFlowId`:string,
                `keyFingerprint`:string,
                `keyMaterial`:string,
                `keyName`:string,
                `keyPairId`:string,
                `licenseModel`:string,
                `majorEngineVersion`:string,
                `masterUsername`:string,
                `monitoringInterval`:bigint,
                `multiAZ`:boolean,
                `networkInterface`:struct<
                    `availabilityZone`:string,
                    `description`:string,
                    `groupSet`:struct<
                        `items`:array<
                            struct<
                                `groupId`:string,
                                `groupName`:string>>>,
                    `interfaceType`:string,
                    `macAddress`:string,
                    `networkInterfaceId`:string,
                    `ownerId`:string,
                    `privateDnsName`:string,
                    `privateIpAddress`:string,
                    `privateIpAddressesSet`:struct<
                        `item`:array<
                            struct<
                                `primary`:boolean,
                                `privateDnsName`:string,
                                `privateIpAddress`:string>>>,
                    `requesterId`:string,
                    `requesterManaged`:boolean,
                    `sourceDestCheck`:boolean,
                    `status`:string,
                    `subnetId`:string,
                    `vpcId`:string>,
                `optionGroupArn`:string,
                `optionGroupDescription`:string,
                `optionGroupMemberships`:array<
                    struct<
                        `optionGroupName`:string,
                        `status`:string>>,
                `optionGroupName`:string,
                `options`:array<
                    struct<
                        `dBSecurityGroupMemberships`:array<
                            string>,
                        `optionDescription`:string,
                        `optionName`:string,
                        `optionSettings`:array<
                            struct<
                                `applyType`:string,
                                `dataType`:string,
                                `description`:string,
                                `isCollection`:boolean,
                                `isModifiable`:boolean,
                                `name`:string,
                                `value`:string>>,
                        `permanent`:boolean,
                        `persistent`:boolean,
                        `vpcSecurityGroupMemberships`:array<
                            string>>>,
                `ownerId`:string,
                `packedPolicySize`:bigint,
                `parameters`:array<
                    struct<
                        `description`:string,
                        `noEcho`:boolean,
                        `parameterKey`:string,
                        `parameterType`:string>>,
                `pendingModifiedValues`:struct<
                    `masterUserPassword`:string>,
                `performanceInsightsEnabled`:boolean,
                `preferredBackupWindow`:string,
                `preferredMaintenanceWindow`:string,
                `publiclyAccessible`:boolean,
                `queryExecutionId`:string,
                `readReplicaDBInstanceIdentifiers`:array<
                    string>,
                `recommendationGroups`:array<
                    struct<
                        `count`:bigint,
                        `docLink`:string,
                        `groupDescription`:string,
                        `groupKey`:string,
                        `groupParameters`:array<
                            string>,
                        `groupTitle`:string,
                        `helpText`:string>>,
                `recommendations`:array<
                    struct<
                        `recommendationActions`:array<
                            string>,
                        `recommendationApplyNowActions`:array<
                            struct<
                                `actionCode`:string,
                                `actionParameters`:array<
                                    struct<
                                        `key`:string,
                                        `value`:string>>>>,
                        `recommendationCode`:string,
                        `recommendationCreateTime`:string,
                        `recommendationModifyTime`:string,
                        `recommendationNextMaintenanceActions`:array<
                            struct<
                                `actionCode`:string,
                                `actionParameters`:array<
                                    struct<
                                        `key`:string,
                                        `value`:string>>>>,
                        `recommendationParameters`:array<
                            struct<
                                `key`:string,
                                `value`:string>>,
                        `recommendationStatus`:string,
                        `recommendationText`:string,
                        `resourceIdentifier`:string>>,
                `requestId`:string,
                `requesterId`:string,
                `reservationId`:string,
                `securityConfigurations`:array<
                    string>,
                `stackId`:string,
                `storageEncrypted`:boolean,
                `storageType`:string,
                `subnet`:struct<
                    `assignIpv6AddressOnCreation`:boolean,
                    `availabilityZone`:string,
                    `availableIpAddressCount`:bigint,
                    `cidrBlock`:string,
                    `defaultForAz`:boolean,
                    `mapPublicIpOnLaunch`:boolean,
                    `state`:string,
                    `subnetId`:string,
                    `vpcId`:string>,
                `subnetGroupStatus`:string,
                `subnets`:array<
                    struct<
                        `subnetAvailabilityZone`:struct<
                            `name`:string>,
                        `subnetIdentifier`:string,
                        `subnetStatus`:string>>,
                `tagList`:array<
                    struct<
                        `key`:string,
                        `value`:string>>,
                `url`:string,
                `vpc`:struct<
                    `cidrBlock`:string,
                    `cidrBlockAssociationSet`:struct<
                        `items`:array<
                            struct<
                                `associationId`:string,
                                `cidrBlock`:string,
                                `cidrBlockState`:struct<
                                    `state`:string>>>>,
                    `dhcpOptionsId`:string,
                    `instanceTenancy`:string,
                    `isDefault`:boolean,
                    `state`:string,
                    `vpcId`:string>,
                `vpcId`:string,
                `vpcSecurityGroups`:array<
                    struct<
                        `status`:string,
                        `vpcSecurityGroupId`:string>>,
                `workGroup`:struct<
                    `configuration`:struct<
                        `enforceWorkGroupConfiguration`:boolean,
                        `publishCloudWatchMetricsEnabled`:boolean,
                        `requesterPaysEnabled`:boolean,
                        `resultConfiguration`:struct<
                            `outputLocation`:string>>,
                    `creationTime`:string,
                    `description`:string,
                    `name`:string,
                    `state`:string>,
                `yarnApplicationSummaries`:array<
                    struct<
                        `appId`:string,
                        `currentAppAttemptId`:string,
                        `diagnosticsInfo`:string,
                        `elapsedTime`:bigint,
                        `finalAppStatus`:string,
                        `finishedTime`:bigint,
                        `host`:string,
                        `name`:string,
                        `originalTrackingUrl`:string,
                        `progress`:double,
                        `queue`:string,
                        `rpcPort`:bigint,
                        `startedTime`:bigint,
                        `submittedTime`:bigint,
                        `trackingUrl`:string,
                        `type`:string,
                        `user`:string>>>,
            `serviceEventDetails`:struct<
                `snapshotId`:string>,
            `sharedEventID`:string,
            `sourceIPAddress`:string,
            `userAgent`:string,
            `userIdentity`:struct<
                `accessKeyId`:string,
                `accountId`:string,
                `arn`:string,
                `invokedBy`:string,
                `principalId`:string,
                `sessionContext`:struct<
                    `attributes`:struct<
                        `creationDate`:string,
                        `mfaAuthenticated`:string>,
                    `ec2RoleDelivery`:string,
                    `sessionIssuer`:struct<
                        `accountId`:string,
                        `arn`:string,
                        `principalId`:string,
                        `type`:string,
                        `userName`:string>>,
                `type`:string>,
            `vpcEndpointId`:string>>)

PARTITIONED BY (`region` string, `dt` string)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES ('ignore.malformed.json' = 'true')
STORED AS INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 's3://my-cloudtrail-log-bucket/AWSLogs/123456789012/CloudTrail/'

-- ALTER TABLE cloudtrail add partition (region='ap-southeast-2', dt='2020-10-08')
-- location 's3://my-cloudtrail-log-bucket/AWSLogs/123456789012/CloudTrail/ap-southeast-2/2020/10/08'